spring.application.name=estoque

server.port = 8081

# --- CONFIGURACOES DO RABBITMQ ---
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


spring.rabbitmq.listener.simple.default-requeue-rejected=false


spring.datasource.url=jdbc:postgresql://ms-db:5432/ms
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Como nós já estamos criando a tabela no init.sql, mandamos o Hibernate só "validar" ou "atualizar", sem apagar nada
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true